### ISSUE TITLE
Recycle process 

### ISSUE THREAD

**Issue by staabm** [amphp/process#20]
Starting and stopping processes is a very time consuming thing.

Would it be possible to leave a process open after the command finished and let it run another command? Or maybe some kind of process pooling to reduce start/stop overhead?

Not sure its possible at all...

**Comment by kelunik** [comment]
That's what https://github.com/amphp/parallel does.

**Comment by staabm** [comment]
Does it support several commands with a single process?

**Comment by kelunik** [comment]
What do you mean with commands?

**Comment by staabm** [comment]
Pseudocode

$process = new process( ...);
$out1 = $process->start(„ls -l“);
$out2 = $process->start(„ls -lott“);
...

All with a single process

The example is simplified, I dont want „ls -l && ls -lotr“ in userland

**Comment by kelunik** [comment]
You're spawning two processes, there's no way around that.

**Comment by staabm** [comment]
Guess it, k thx
