### ISSUE TITLE
Why is wrapper binary used here not using official source code?

### ISSUE THREAD

**Issue by ostrolucky** [amphp/process#28]
I compiled source at https://github.com/amphp/windows-process-wrapper and running it with no arguments yields following message:

> No executable specified

Running executable in this repository yields message:

> Process label not supplied

cc @DaveRandom 

This is blocking me from debugging issue I had

**Comment by DaveRandom** [comment]
The bundled bin is not built from the master branch, it's built from https://github.com/amphp/windows-process-wrapper/tree/stdin-command-passing

I'm not sure exactly what the status is as it was too long ago and I don't have time to dig about in it atm, but at least if you base your builds from that branch you are working with the correct sources.

**Comment by kelunik** [comment]
Closing, as this has been answered. @DaveRandom Could you merge that branch into master then?

**Comment by DaveRandom** [comment]
@kelunik done

**Comment by kelunik** [comment]
@DaveRandom Thanks!
