### ISSUE TITLE
posix/Runner::kill not worked

### ISSUE THREAD

**Issue by Ekstazi** [amphp/process#29]
some example code:
```php
$process = yield Amp\Parallel\Context::run('test.php');
$process->kill();
```

test.php:
```php
sleep(30);
```
As i can see on linux systems(`ps -aux | grep php`) test,php keep runned and detached after end of main script.

This happen because kill only terminate sh but keep php detached.

**Comment by Ekstazi** [comment]
Php bug described here:
http://php.net/manual/ru/function.proc-terminate.php

https://bugs.php.net/bug.php?id=39992,

**Comment by ostrolucky** [comment]
I'm also affected by this. @kelunik @trowski please take inspiration from symfony/process and have less naive killing logic. Just `proc_terminate` is not going to cut it.

**Comment by trowski** [comment]
@ostrolucky I was waiting for @Ekstazi to update the PR to remove the change he made to the travis config… but that didn't happen and I forgot about it. I'll update it myself and merge it.

**Comment by Ekstazi** [comment]
@trowski Sorry. I didn't find way to fix seg fault yet... Can you help me with it ?
