### ISSUE TITLE
amphp/process kills sub process on exit

### ISSUE THREAD

**Issue by ostrolucky** [amphp/process#33]
wrapper.php
```php
<?php
echo 'foo';
sleep(1);
touch('a');
```

Following works as expected, outputs `foo`, exits immediately and after 1 second creates file 'a'.
```php
<?php

$fd = [
    ["pipe", "r"], // stdin
    ["pipe", "w"], // stdout
];
$handle = @\proc_open('php wrapper.php', $fd, $pipes);

echo fread($pipes[1], 100);
```

Following does not work as expected. Outputs `foo`, exits immediately but file is not created.
```php
<?php
require_once "vendor/autoload.php";
\Amp\Loop::run(function () {
    $process = new \Amp\Process\Process("php wrapper.php");
    yield $process->start();
    echo yield $process->getStdout()->read();
});
```

**Comment by trowski** [comment]
If the `Process` object is destroyed while the process is running, the process is killed. If you want to wait for the process to finish execution, you need to wait on the promise returned from `Process::join()`.

**Comment by ostrolucky** [comment]
I don't want to wait, I want to exit immediately and let process finish in background

**Comment by kelunik** [comment]
Currently we don't directly support daemonizing child processes. Maybe you can get it work with `nohup` / `setsid`? I tried, but I failed.

**Comment by ostrolucky** [comment]
Yeah I don't know how to do that either, what you currently use at https://github.com/amphp/process/blob/355b1e561b01c16ab3d78fada1ad47ccc96df70e/lib/Internal/Posix/Runner.php#L82-L83 is black magic for me.

Please remove wrong label.

**Comment by trowski** [comment]
A possible solution is adding a method to `Process`, perhaps `daemonize()`, that sets a flag to not automatically kill the child process when the `Process` object is destroyed. The current default behavior would not be altered, but that would enable what @ostrolucky is trying to accomplish.

**Comment by ostrolucky** [comment]
yeah that would work for me

**Comment by kelunik** [comment]
This won't be supported for now, because the process would have to be properly disowned to avoid zombie processes.
