### ISSUE TITLE
Assert Function in Process Class

### ISSUE THREAD

**Issue by TomKita** [amphp/process#4]
I think there is a left over Assert Function on line 73 of the Process class. Should this be removed?

**Comment by bwoebi** [comment]
line 73? The only assert I see is on line 201: https://github.com/amphp/process/blob/master/Process.php#L201

Which isn't exactly a leftover, but I agree that a conventional InvalidArgumentException would be fitting better here…?

**Comment by kelunik** [comment]
An empty string for `write` should just be ignored IMO.

**Comment by TomKita** [comment]
@bwoebi Sorry I was looking at Tag 0.1.1. Seems to be removed in dev-master. I agree with @bwoebi that an InvalidArgumentException should be thrown. Otherwise why call write() if nothing should be written?

**Comment by bwoebi** [comment]
Okay, going to tag 0.1.2 tomorrow after having put an InvalidArgumentException there.

**Comment by kelunik** [comment]
It should also check the type then.

**Comment by bwoebi** [comment]
@TomKita done :)
