### ISSUE TITLE
Undefined property: Amp\Process::$proc

### ISSUE THREAD

**Issue by ncraike** [amphp/process#9]
When running a sub-process within Amp using `Process`, I sometimes see these notices output in logs:
```
Undefined property: Amp\Process::$proc in /var/www/vendor/amphp/process/Process.php on line 178
```
and:
```
[2017-02-15 06:41:41] notice Undefined property: Amp\Process::$proc in /var/www/vendor/amphp/process/Process.php on line 224
```
These seem to be from `$this->proc` in the `cancel()` and `pid()` methods.

I understand that notices are mostly harmless, but is there some way this code could be rewritten to avoid giving notices?

**Comment by kelunik** [comment]
Instead of unsetting it in `cancel`, it should be set to `null` there.

**Comment by kelunik** [comment]
Not sure if it's worth fixing. Please upgrade to v0.3.0 instead.
